FROM python:3.11-slim
# Image Linux avec Python

WORKDIR /app
# Dossier de travail dans le container

COPY requirements.txt .
RUN pip install --no-cache-dir \
    torch==2.3.1 \
    torchvision==0.18.1 \
    --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir -r requirements.txt
# Installe les dépendances

COPY src/ src/
# Copie ton code

CMD ["python", "-m", "src.api.main"]
# Lance l’API par défaut
